name: AywenCraftPlugin
version: '${version}'
main: fr.communaywen.core.AywenCraftPlugin
api-version: '1.20'

commands:
  version:
    description: Affiche la version du plugin.
  team:
    description: Commande pour gérer les équipes
