name: AywenCraftPlugin
version: 1.0
main: fr.communaywen.core.AywenCraftPlugin
description: Plugin pour changer le MOTD toutes les 10 minutes

commands:
  version:
    description: Affiche la version du plugin.
