name: AywenCraftPlugin
version: '${version}'
main: fr.communaywen.core.AywenCraftPlugin
api-version: '1.20'

commands:
  version:
    description: Affiche la version du plugin.
    permission: ayw.version
    permission-message: "Vous n'avez pas la permission d'utiliser cette commande."
  prout:
    description: Prout !
    permission: ayw.command.prout

permissions:
  ayw.admin.version:
    description: Permission pour utiliser la commande /version
    default: op
  ayw.command.prout:
    description: 'Prout !'
    default: true
