name: Build DEV Jars
on: [push, pull_request]
jobs:
  build_dev_jars:
    name: Build DEV jars
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Build with Gradle
        run: |
          chmod 777 gradlew
          ./gradlew jar
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "git_hash=$git_hash" >> $GITHUB_ENV
          echo "snapshotVersion=5.5-SNAPSHOT" >> $GITHUB_ENV
          echo "artifactPath=$(pwd)/builds" >> $GITHUB_ENV
      - name: Upload Plugin jar
        uses: actions/upload-artifact@v3
        with:
          name: AywenCraft-${{ env.git_hash }}.jar
          path: ${{ env.artifactPath }}/core-1.0-SNAPSHOT.jar
      - name: Upload to mc (sftp)
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{secrets.IP}}
          username: ${{secrets.USER}}
          password: ${{secrets.PASSWD}}
          port: 2022
          uploads: |
            ${{ env.artifactPath }}/core-1.0-SNAPSHOT.jar => ./plugins/AywenCraft.jar
